#!/usr/bin/env bash


get_record_info() {
    domain="$1"
    subdomain="$2"
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short "$sub"."$domain" | awk '{print toupper($1)}')
        destination=$(dig +short "$sub"."$domain" | awk '{print $1}')
        if [ -z "$destination" ]; then
            echo "The subdomain $sub does not exist."
        else
            echo "The subdomain $sub is a $record_type record and points to $destination"
        fi
    done
}

get_record_info "$1" "$2"

