#!/usr/bin/env bash
#In between every I am alive! message, the program should pause for 2 seconds
#Indefinitely writes I am alive! to the file /tmp/my_process
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process started

case "$1" in
    start)
        ./manage_my_process.sh start
        ;;
    stop)
        ./manage_my_process.sh stop
        ;;
    restart)
        ./manage_my_process.sh restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
