#!/usr/bin/env bash
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process restarted

while true
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
